apiVersion: apps/v1
kind: Deployment
metadata:
  name: postmortemdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postmortemdeployment
  template:
    metadata:
      labels:
        app: postmortemdeployment
    spec:
      containers:
      - name: postmortemdeployment
        image: outk/postmortem:v0.0.1
        ports:
        - containerPort: 8080
